# Hyprland Main Configuration File
# Sourced configurations

source = ~/.config/hypr/cfg/monitors.conf
source = ~/.config/hypr/cfg/autostart.conf
source = ~/.config/hypr/cfg/theme.conf
source = ~/.config/hypr/cfg/input.conf
source = ~/.config/hypr/cfg/keybinds.conf
source = ~/.config/hypr/cfg/animations.conf
source = ~/.config/hypr/cfg/rules.conf
source = ~/.config/hypr/cfg/misc.conf
