# ─── Window & Layer Rules ───

# Steam & Dialog Floating Rules
windowrule=appid:steam,isfloating:1
windowrule=appid:pavucontrol,isfloating:1
windowrule=appid:nm-connection-editor,isfloating:1
windowrule=appid:blueberry.py,isfloating:1
windowrule=appid:org.gnome.Nautilus,isfloating:0

# Full opacity for media/browsers/editor
windowrule=appid:zen,focused_opacity:1.0,unfocused_opacity:0.90
windowrule=appid:code,focused_opacity:1.0,unfocused_opacity:0.90
windowrule=appid:firefox,focused_opacity:1.0,unfocused_opacity:0.90
windowrule=appid:equibop,focused_opacity:1.0,unfocused_opacity:0.90

# # Noctalia layer surfaces — disable blur & shadow to prevent wallpaper bleed
# layerrule=layer_name:noctalia-.*,noblur:1
# layerrule=layer_name:noctalia-.*,noshadow:1
