# ────────────── Animations Configuration ──────────────

animations {
    enabled = true

    # Bezier Curves
    bezier = easeOutQuad, 0.25, 0.46, 0.45, 0.94
    bezier = easeOutCubic, 0.215, 0.61, 0.355, 1
    bezier = fluent, 0.05, 0.9, 0.1, 1.0
    bezier = overshot, 0.05, 0.9, 0.1, 1.05

    # Animation styles
    animation = windows, 1, 4, fluent, slide
    animation = windowsOut, 1, 3.5, easeOutCubic, slide
    animation = windowsIn, 1, 4, fluent, slide
    animation = windowsMove, 1, 4, fluent
    
    animation = border, 1, 5, default
    animation = borderangle, 1, 5, default
    animation = fade, 1, 4, default
    
    animation = workspaces, 1, 4.5, fluent, slide
}
