# ────────────── Startup Applications ──────────────

exec-once = noctalia-shell
exec-once = equibop
exec-once = wayland-pipewire-idle-inhibit
exec-once = systemctl --user start graphical-session.target
