# ─── MangoWM Main Configuration ───
# https://mangowm.github.io/docs/

source=~/.config/mango/cfg/env.conf
source=~/.config/mango/cfg/autostart.conf
source=~/.config/mango/cfg/input.conf
source=~/.config/mango/cfg/display.conf
source=~/.config/mango/cfg/layout.conf
source=~/.config/mango/cfg/rules.conf
source=~/.config/mango/cfg/bind.conf
